/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interficie;

import java.util.Collection;
import java.util.Iterator;

import domini.Categoria;
import domini.GrafDades;
import domini.Pagina;

/**
 *
 * @author Cristina
 */
public class InterficiaProva extends javax.swing.JFrame {
    static domini.MacroControlador macro;
    /**
     * Creates new form InterficiaProva
     */
    public InterficiaProva() {
        initComponents();
        macro = new domini.MacroControlador();
        macro.getContUser().addUser("admin", "admin");
	macro.getContUser().addUser("client", "client");
	macro.getContUser().addAdmin("admin");
        Categoria aux1 = new Categoria("sexualitat"); // Prova Sexualitat
	Categoria aux2 = new Categoria("asexual");
	GrafDades G = macro.getGraf();
	G.addCC(aux1,aux2);
	Categoria aux3 = new Categoria("heterosexual");
	G.addCC(aux1,aux3);
	Categoria aux4 = new Categoria("homosexual");
	G.addCC(aux1, aux4);
	Categoria aux5 = new Categoria("sexe");
	G.addCC(aux1,aux5);
	Categoria aux6 = new Categoria("embaras");
	G.addCC(aux3,aux6);
	G.addCC(aux5, aux6);
	Categoria aux7 = new Categoria("infertil");
	G.addCC(aux4, aux7);
	G.addCC(aux2, aux7);
	G.addCC(aux3,aux4);
	Pagina aux0 = new Pagina("esteril");
	G.addPagina(aux0);
        A_BuscaCat.setVisible(false);
        A_OpcionsClient.setVisible(false);
        A_OpcionsAdmin.setVisible(false);
        Wikipedia.setVisible(true);
       // A_PantallaPrincipal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        Wikipedia = new javax.swing.JInternalFrame();
        A_PantallaPrincipal = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        A_OpcionsClient = new javax.swing.JPanel();
        EnrereC = new javax.swing.JButton();
        BuscaCategories = new javax.swing.JButton();
        BuscaPagines = new javax.swing.JButton();
        BuscaCatPag = new javax.swing.JButton();
        CreaCerca = new javax.swing.JButton();
        BuscaCerques = new javax.swing.JButton();
        A_OpcionsAdmin = new javax.swing.JPanel();
        A_BuscaCat = new javax.swing.JPanel();
        BOpC = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        LlistaCateg = new javax.swing.JList();
        BVisCat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prova1");

        Wikipedia.setClosable(true);
        Wikipedia.setIconifiable(true);
        Wikipedia.setMaximizable(true);
        Wikipedia.setTitle("Wikipedia");
        Wikipedia.setToolTipText("whereeee?");
        Wikipedia.setAutoscrolls(true);
        Wikipedia.setDoubleBuffered(true);
        Wikipedia.setInheritsPopupMenu(true);
        Wikipedia.setName("Wikipedia_where?"); // NOI18N
        try {
            Wikipedia.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        Wikipedia.setVisible(true);

        javax.swing.GroupLayout WikipediaLayout = new javax.swing.GroupLayout(Wikipedia.getContentPane());
        Wikipedia.getContentPane().setLayout(WikipediaLayout);
        WikipediaLayout.setHorizontalGroup(
            WikipediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );
        WikipediaLayout.setVerticalGroup(
            WikipediaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton4.setText("JPanelForm1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Benvingut al programa de la wikipedia");

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Login.setText("Login");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        Login.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                LoginStateChanged(evt);
            }
        });
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Si us plau, entra les teves dades. Si encara no tens cap usuari assignat, pots Crear-ne un de nou :)");

        Username.setText("client");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Username:");

        jLabel4.setText("Password:");

        Password.setText("client");

        javax.swing.GroupLayout A_PantallaPrincipalLayout = new javax.swing.GroupLayout(A_PantallaPrincipal);
        A_PantallaPrincipal.setLayout(A_PantallaPrincipalLayout);
        A_PantallaPrincipalLayout.setHorizontalGroup(
            A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel3))
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Login))
                            .addComponent(jLabel1)
                            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                                        .addComponent(jButton4)
                                        .addGap(140, 140, 140)
                                        .addComponent(Exit))
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        A_PantallaPrincipalLayout.setVerticalGroup(
            A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(Login)))
                .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(Exit))
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton4)))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        Username.getAccessibleContext().setAccessibleName("Username");

        EnrereC.setText("Enrere");
        EnrereC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereCActionPerformed(evt);
            }
        });

        BuscaCategories.setText("Busca entre les Categories");
        BuscaCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCategoriesActionPerformed(evt);
            }
        });

        BuscaPagines.setText("Busca entre les Pàgines");

        BuscaCatPag.setText("Busca entre les Categories i Pàgines");
        BuscaCatPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCatPagActionPerformed(evt);
            }
        });

        CreaCerca.setText("Crea una nova Cerca de Comunitats ");

        BuscaCerques.setText("Visualitza Cerques realitzades anteriorment");

        javax.swing.GroupLayout A_OpcionsClientLayout = new javax.swing.GroupLayout(A_OpcionsClient);
        A_OpcionsClient.setLayout(A_OpcionsClientLayout);
        A_OpcionsClientLayout.setHorizontalGroup(
            A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_OpcionsClientLayout.createSequentialGroup()
                .addGroup(A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BuscaPagines, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscaCategories, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscaCatPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreaCerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscaCerques, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addGap(150, 150, 150)
                .addComponent(EnrereC)
                .addGap(0, 171, Short.MAX_VALUE))
        );
        A_OpcionsClientLayout.setVerticalGroup(
            A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, A_OpcionsClientLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(BuscaCategories)
                .addGroup(A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_OpcionsClientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BuscaPagines))
                    .addGroup(A_OpcionsClientLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(EnrereC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscaCatPag)
                .addGap(18, 18, 18)
                .addComponent(CreaCerca)
                .addGap(18, 18, 18)
                .addComponent(BuscaCerques)
                .addContainerGap(378, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout A_OpcionsAdminLayout = new javax.swing.GroupLayout(A_OpcionsAdmin);
        A_OpcionsAdmin.setLayout(A_OpcionsAdminLayout);
        A_OpcionsAdminLayout.setHorizontalGroup(
            A_OpcionsAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        A_OpcionsAdminLayout.setVerticalGroup(
            A_OpcionsAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        BOpC.setText("Enrere");
        BOpC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOpCActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("Aquestes són les categories existents:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        LlistaCateg.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LlistaCateg.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextField1, org.jdesktop.beansbinding.ObjectProperty.create(), LlistaCateg, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        binding.setSourceNullValue(null);
        bindingGroup.addBinding(binding);

        BVisCat.setText("Visualitza");
        BVisCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVisCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout A_BuscaCatLayout = new javax.swing.GroupLayout(A_BuscaCat);
        A_BuscaCat.setLayout(A_BuscaCatLayout);
        A_BuscaCatLayout.setHorizontalGroup(
            A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaCatLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(BVisCat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(A_BuscaCatLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(BOpC)
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addComponent(LlistaCateg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        A_BuscaCatLayout.setVerticalGroup(
            A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaCatLayout.createSequentialGroup()
                .addGroup(A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BOpC))
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(LlistaCateg, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(BVisCat)
                .addGap(326, 326, 326))
        );

        LlistaCateg.getAccessibleContext().setAccessibleName("LlistaCateg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(A_PantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(A_OpcionsClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_OpcionsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_BuscaCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(333, 333, 333)
                    .addComponent(Wikipedia)
                    .addContainerGap(333, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(A_PantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(A_OpcionsClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_OpcionsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_BuscaCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(314, 314, 314)
                    .addComponent(Wikipedia, 0, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        Wikipedia.getAccessibleContext().setAccessibleName("Wikipedia");

        getAccessibleContext().setAccessibleDescription("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String user, pass;
        user= Username.getText();
        pass= Password.getText();
        if(!macro.getContUser().existsUser(user)) {
            ErrorUsername aux = new ErrorUsername(this,true);
            aux.setVisible(true);
        }
        else if(macro.getContUser().login(user, pass)){
            A_PantallaPrincipal.setVisible(false);
            if(macro.getContUser().isAdmin(user)) A_OpcionsAdmin.setVisible(true);
            else A_OpcionsClient.setVisible(true);
        }
        else {
            ErrorPassword aux = new ErrorPassword(this,true);
            aux.setVisible(true);
        }
         
       // }
       
// TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void LoginStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_LoginStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginStateChanged

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //JPanelForm1 aux = new JPanelForm1();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EnrereCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereCActionPerformed
        A_PantallaPrincipal.setVisible(true);
        A_OpcionsClient.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_EnrereCActionPerformed

    private void BuscaCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCategoriesActionPerformed
        A_OpcionsClient.setVisible(false);
        A_BuscaCat.setVisible(true);
       // BOpC.setVisible(true);
        Object aux = new Object();
        aux = macro.getGraf().getCategories();
        Collection<Categoria> auxc = macro.getGraf().getCategories();
        Object[] aux2 = new Object[auxc.size()];
        int cont = 0;
        Iterator<Categoria> it = auxc.iterator();
        while(it.hasNext()) {
            aux2[cont] = it.next().getNom();
            ++cont;
        }
        LlistaCateg.setListData(aux2);
      //  LlistaCateg.setVisible(true);
       // A_BuscaCat.setVisible(true);
        
        //jList1.add(javax.swing.JTextField);
// TODO add your handling code here:
    }//GEN-LAST:event_BuscaCategoriesActionPerformed

    private void BuscaCatPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCatPagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscaCatPagActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void BOpCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOpCActionPerformed
        A_OpcionsClient.setVisible(true);// TODO add your handling code here:
        A_BuscaCat.setVisible(false);
    }//GEN-LAST:event_BOpCActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BVisCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVisCatActionPerformed
        VCategoria aux = new VCategoria(this,true);
        aux.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_BVisCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterficiaProva().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A_BuscaCat;
    private javax.swing.JPanel A_OpcionsAdmin;
    private javax.swing.JPanel A_OpcionsClient;
    private javax.swing.JPanel A_PantallaPrincipal;
    private javax.swing.JButton BOpC;
    private javax.swing.JButton BVisCat;
    private javax.swing.JButton BuscaCatPag;
    private javax.swing.JButton BuscaCategories;
    private javax.swing.JButton BuscaCerques;
    private javax.swing.JButton BuscaPagines;
    private javax.swing.JButton CreaCerca;
    private javax.swing.JButton EnrereC;
    private javax.swing.JButton Exit;
    private javax.swing.JList LlistaCateg;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JInternalFrame Wikipedia;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
