/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interficie;

import java.awt.Component;
import java.util.Collection;
import java.util.Iterator;
import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.ListCellRenderer;
import javax.swing.ListModel;

import domini.Categoria;
import domini.GrafDades;
import domini.Pagina;
import java.awt.Rectangle;

/**
 *
 * @author Cristina
 */
public class InterficiaProva extends javax.swing.JFrame {
    static domini.MacroControlador macro;
    //Object[] Csubcat;
    /**
     * Creates new form InterficiaProva
     */
    public InterficiaProva() {
        initComponents();
        macro = new domini.MacroControlador();
        macro.getContUser().addUser("admin", "admin");
	macro.getContUser().addUser("client", "client");
	macro.getContUser().addAdmin("admin");
        Categoria aux1 = new Categoria("sexualitat"); // Prova Sexualitat
	Categoria aux2 = new Categoria("asexual");
	GrafDades G = macro.getGraf();
	G.addCC(aux1,aux2);
	Categoria aux3 = new Categoria("heterosexual");
	G.addCC(aux1,aux3);
	Categoria aux4 = new Categoria("homosexual");
	G.addCC(aux1, aux4);
	Categoria aux5 = new Categoria("sexe");
	G.addCC(aux1,aux5);
	Categoria aux6 = new Categoria("embaras");
	G.addCC(aux3,aux6);
	G.addCC(aux5, aux6);
	Categoria aux7 = new Categoria("infertil");
	G.addCC(aux4, aux7);
	G.addCC(aux2, aux7);
	G.addCC(aux3,aux4);
	Pagina aux0 = new Pagina("esteril");
	G.addPagina(aux0);
        G.addCP(aux7, aux0);
        G.addPC(aux0, aux6);
        A_BuscaCat.setVisible(false);
        A_BuscaPag.setVisible(false);
        A_OpcionsClient.setVisible(false);
        A_OpcionsAdmin.setVisible(false);
        A_BuscaCatPag.setVisible(false);
        A_CreaComunitat.setVisible(false);
        A_CreaUsuari.setVisible(false);
        //Wikipedia.setVisible(true);
       // A_PantallaPrincipal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        A_PantallaPrincipal = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        A_CreaUsuari = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NouUsername = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        NovaPassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        A_OpcionsClient = new javax.swing.JPanel();
        EnrereC = new javax.swing.JButton();
        BuscaCategories = new javax.swing.JButton();
        BuscaPagines = new javax.swing.JButton();
        BuscaCatPag = new javax.swing.JButton();
        CreaCerca = new javax.swing.JButton();
        BuscaCerques = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        A_OpcionsAdmin = new javax.swing.JPanel();
        A_BuscaCat = new javax.swing.JPanel();
        BOpC = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        BVisCat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        LlistaCateg = new javax.swing.JList();
        A_BuscaPag = new javax.swing.JPanel();
        BOpC1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        BVisPag = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        LlistaPag = new javax.swing.JList();
        A_BuscaCatPag = new javax.swing.JPanel();
        BVisPag1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        BVisCat1 = new javax.swing.JButton();
        BOpC2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        LlistaCateg1 = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        LlistaPag1 = new javax.swing.JList();
        A_CreaComunitat = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Cpc = new javax.swing.JTextField();
        Crelacio = new javax.swing.JSlider();
        Cbusca = new javax.swing.JTextField();
        Cafegeix1 = new javax.swing.JButton();
        CbuscaCat = new javax.swing.JButton();
        Csembla = new javax.swing.JSlider();
        CpcImp = new javax.swing.JSlider();
        EliminaCsub = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        LCTotes = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        modelo = new DefaultListModel();
        Lsub = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        LPTotes = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prova1");

        jButton4.setText("Crea un nou usuari");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Benvingut al programa de la wikipedia");

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        Login.setText("Login");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        jLabel1.setText("Si us plau, entra les teves dades. Si encara no tens cap usuari assignat, pots Crear-ne un de nou :)");

        Username.setText("client");
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });

        jLabel2.setText("Username:");

        jLabel4.setText("Password:");

        Password.setText("client");

        javax.swing.GroupLayout A_PantallaPrincipalLayout = new javax.swing.GroupLayout(A_PantallaPrincipal);
        A_PantallaPrincipal.setLayout(A_PantallaPrincipalLayout);
        A_PantallaPrincipalLayout.setHorizontalGroup(
            A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel3))
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Login))
                            .addComponent(jLabel1)
                            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                                        .addGap(263, 263, 263)
                                        .addComponent(Exit))
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton4)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        A_PantallaPrincipalLayout.setVerticalGroup(
            A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(A_PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(A_PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel3)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(Login)))
                .addGap(45, 45, 45)
                .addComponent(jButton4)
                .addGap(2, 2, 2)
                .addComponent(Exit)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        Username.getAccessibleContext().setAccessibleName("Username");

        jLabel7.setText("Creació d'un nou usuari");

        NouUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NouUsernameActionPerformed(evt);
            }
        });

        jLabel8.setText("Username");

        jButton1.setText("Comproba Disponibilitat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Password");

        NovaPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaPasswordActionPerformed(evt);
            }
        });

        jButton2.setText("Crea");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Enrere");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout A_CreaUsuariLayout = new javax.swing.GroupLayout(A_CreaUsuari);
        A_CreaUsuari.setLayout(A_CreaUsuariLayout);
        A_CreaUsuariLayout.setHorizontalGroup(
            A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                .addGroup(A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel7))
                    .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                                .addGroup(A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(jButton2))
                                    .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(38, 38, 38)
                                        .addComponent(NouUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addComponent(jButton1))
                            .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(40, 40, 40)
                                .addComponent(NovaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(jButton3)))))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        A_CreaUsuariLayout.setVerticalGroup(
            A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addGroup(A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NouUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButton1))
                .addGroup(A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, A_CreaUsuariLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(NovaPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(A_CreaUsuariLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(A_CreaUsuariLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jLabel9))
                        .addGap(26, 26, 26)))
                .addComponent(jButton2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        EnrereC.setText("Enrere");
        EnrereC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrereCActionPerformed(evt);
            }
        });

        BuscaCategories.setText("Busca entre les Categories");
        BuscaCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCategoriesActionPerformed(evt);
            }
        });

        BuscaPagines.setText("Busca entre les Pàgines");
        BuscaPagines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaPaginesActionPerformed(evt);
            }
        });

        BuscaCatPag.setText("Busca entre les Categories i Pàgines");
        BuscaCatPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaCatPagActionPerformed(evt);
            }
        });

        CreaCerca.setText("Crea una nova Cerca de Comunitats ");
        CreaCerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreaCercaActionPerformed(evt);
            }
        });

        BuscaCerques.setText("Visualitza Cerques realitzades anteriorment");

        jButton5.setText("Canvia les dades d'usuari");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Afegeix fitxer");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout A_OpcionsClientLayout = new javax.swing.GroupLayout(A_OpcionsClient);
        A_OpcionsClient.setLayout(A_OpcionsClientLayout);
        A_OpcionsClientLayout.setHorizontalGroup(
            A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_OpcionsClientLayout.createSequentialGroup()
                .addGroup(A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_OpcionsClientLayout.createSequentialGroup()
                        .addGroup(A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BuscaPagines, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscaCategories, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscaCatPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreaCerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscaCerques, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(150, 150, 150)
                        .addComponent(EnrereC))
                    .addComponent(jButton6))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        A_OpcionsClientLayout.setVerticalGroup(
            A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, A_OpcionsClientLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(BuscaCategories)
                .addGroup(A_OpcionsClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_OpcionsClientLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BuscaPagines))
                    .addGroup(A_OpcionsClientLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(EnrereC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscaCatPag)
                .addGap(18, 18, 18)
                .addComponent(CreaCerca)
                .addGap(18, 18, 18)
                .addComponent(BuscaCerques)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout A_OpcionsAdminLayout = new javax.swing.GroupLayout(A_OpcionsAdmin);
        A_OpcionsAdmin.setLayout(A_OpcionsAdminLayout);
        A_OpcionsAdminLayout.setHorizontalGroup(
            A_OpcionsAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );
        A_OpcionsAdminLayout.setVerticalGroup(
            A_OpcionsAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        BOpC.setText("Enrere");
        BOpC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOpCActionPerformed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(240, 240, 240));
        jTextField1.setText("Aquestes són les categories existents:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        BVisCat.setText("Visualitza");
        BVisCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVisCatActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setAutoscrolls(true);

        LlistaCateg.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        LlistaCateg.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LlistaCateg.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jTextField1, org.jdesktop.beansbinding.ObjectProperty.create(), LlistaCateg, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        binding.setSourceNullValue(null);
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(LlistaCateg);
        LlistaCateg.getAccessibleContext().setAccessibleName("LlistaCateg");

        javax.swing.GroupLayout A_BuscaCatLayout = new javax.swing.GroupLayout(A_BuscaCat);
        A_BuscaCat.setLayout(A_BuscaCatLayout);
        A_BuscaCatLayout.setHorizontalGroup(
            A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaCatLayout.createSequentialGroup()
                .addGroup(A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)
                        .addComponent(BOpC))
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(BVisCat)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        A_BuscaCatLayout.setVerticalGroup(
            A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaCatLayout.createSequentialGroup()
                .addGroup(A_BuscaCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BOpC))
                    .addGroup(A_BuscaCatLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BVisCat)
                .addContainerGap())
        );

        BOpC1.setText("Enrere");
        BOpC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOpC1ActionPerformed(evt);
            }
        });

        jTextField2.setBackground(new java.awt.Color(240, 240, 240));
        jTextField2.setText("Aquestes són les pàgines existents:");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        BVisPag.setText("Visualitza");
        BVisPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVisPagActionPerformed(evt);
            }
        });

        LlistaPag.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        LlistaPag.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LlistaPag.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(LlistaPag);

        javax.swing.GroupLayout A_BuscaPagLayout = new javax.swing.GroupLayout(A_BuscaPag);
        A_BuscaPag.setLayout(A_BuscaPagLayout);
        A_BuscaPagLayout.setHorizontalGroup(
            A_BuscaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaPagLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183)
                .addComponent(BOpC1)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(A_BuscaPagLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addGroup(A_BuscaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BVisPag))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        A_BuscaPagLayout.setVerticalGroup(
            A_BuscaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaPagLayout.createSequentialGroup()
                .addGroup(A_BuscaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_BuscaPagLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BOpC1))
                    .addGroup(A_BuscaPagLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BVisPag)
                .addGap(71, 71, 71))
        );

        BVisPag1.setText("Visualitza");
        BVisPag1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVisPag1ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(240, 240, 240));
        jTextField3.setText("Aquestes són les pàgines existents:");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        BVisCat1.setText("Visualitza");
        BVisCat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVisCat1ActionPerformed(evt);
            }
        });

        BOpC2.setText("Enrere");
        BOpC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOpC2ActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(240, 240, 240));
        jTextField4.setText("Aquestes són les categories existents:");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        LlistaCateg1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        LlistaCateg1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LlistaCateg1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(LlistaCateg1);

        LlistaPag1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 51)));
        LlistaPag1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        LlistaPag1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(LlistaPag1);

        javax.swing.GroupLayout A_BuscaCatPagLayout = new javax.swing.GroupLayout(A_BuscaCatPag);
        A_BuscaCatPag.setLayout(A_BuscaCatPagLayout);
        A_BuscaCatPagLayout.setHorizontalGroup(
            A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaCatPagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_BuscaCatPagLayout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BOpC2))
                    .addGroup(A_BuscaCatPagLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 106, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(A_BuscaCatPagLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(BVisCat1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BVisPag1)
                .addGap(128, 128, 128))
        );
        A_BuscaCatPagLayout.setVerticalGroup(
            A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_BuscaCatPagLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_BuscaCatPagLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)
                        .addGroup(A_BuscaCatPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BVisCat1)
                            .addComponent(BVisPag1)))
                    .addGroup(A_BuscaCatPagLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(BOpC2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Benvingut a la creació d'una nova Cerca de Comunitats!");

        jLabel6.setText("Si us plau, omple totes les dades amb un * i tingues en compte les restriccions de les altres");

        jLabel10.setText("Indica amb un numero del 0 al 10 la importància que li vols dnar a la relació entre categopries.");

        jLabel11.setText("0 només premia a les relacions amb les pàgines, un 5 premia igual les relacions cat-cat que les cat-pag i un 10 només premia les relacions cat-cat");

        jLabel12.setText("Indica amb un número del 0 al 10 la importància que li vols donar  a la semblança entre els noms de les categories");

        jLabel13.setText("Indica una paraula clau que vols que es tingui en compte i la seva importància:");

        jLabel14.setText("Un 0 si no en vols cap, un 5 per tal de que les categories que es tinguin en compte tinguin com a mínim la meitat d'aquesta paraula o 10 si l'han de contenir en la seva totalitat");

        jLabel15.setText("Selecciona unes quantes categories entre les quals vols que es faci la cerca");

        jLabel16.setText("Selecciona la categoria pare a partir de la qual es tenen en compte tots els seus fills");

        jLabel17.setText("Selecciona la categoria pare a partir de la qual es tenen en compte tots els seus fills");

        jLabel18.setText("Selecciona unes quantes categories i/o pàgines les quals vols ignorar");

        Crelacio.setForeground(new java.awt.Color(0, 0, 153));
        Crelacio.setMajorTickSpacing(1);
        Crelacio.setMaximum(10);
        Crelacio.setMinorTickSpacing(1);
        Crelacio.setPaintLabels(true);
        Crelacio.setPaintTicks(true);
        Crelacio.setSnapToTicks(true);
        Crelacio.setValue(5);
        Crelacio.setAutoscrolls(true);
        Crelacio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Crelacio.setInheritsPopupMenu(true);
        Crelacio.setValueIsAdjusting(true);

        Cafegeix1.setText("Afegeix");
        Cafegeix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cafegeix1ActionPerformed(evt);
            }
        });

        CbuscaCat.setText("Busca");
        CbuscaCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbuscaCatActionPerformed(evt);
            }
        });

        Csembla.setForeground(new java.awt.Color(0, 0, 153));
        Csembla.setMajorTickSpacing(1);
        Csembla.setMaximum(10);
        Csembla.setMinorTickSpacing(1);
        Csembla.setPaintLabels(true);
        Csembla.setPaintTicks(true);
        Csembla.setSnapToTicks(true);
        Csembla.setValue(5);
        Csembla.setAutoscrolls(true);
        Csembla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Csembla.setInheritsPopupMenu(true);
        Csembla.setValueIsAdjusting(true);

        CpcImp.setForeground(new java.awt.Color(0, 0, 153));
        CpcImp.setMajorTickSpacing(5);
        CpcImp.setMaximum(10);
        CpcImp.setMinorTickSpacing(5);
        CpcImp.setPaintLabels(true);
        CpcImp.setPaintTicks(true);
        CpcImp.setSnapToTicks(true);
        CpcImp.setValue(0);
        CpcImp.setAutoscrolls(true);
        CpcImp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CpcImp.setInheritsPopupMenu(true);
        CpcImp.setValueIsAdjusting(true);

        EliminaCsub.setText("Elimina");
        EliminaCsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminaCsubActionPerformed(evt);
            }
        });

        LCTotes.setModel(new DefaultListModel());
        jScrollPane5.setViewportView(LCTotes);

        Lsub.setModel(modelo);
        Lsub.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Lsub.setDragEnabled(true);
        Lsub.setDropMode(javax.swing.DropMode.INSERT);
        Lsub.setFocusable(false);
        Lsub.setValueIsAdjusting(true);
        jScrollPane6.setViewportView(Lsub);

        LPTotes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(LPTotes);

        javax.swing.GroupLayout A_CreaComunitatLayout = new javax.swing.GroupLayout(A_CreaComunitat);
        A_CreaComunitat.setLayout(A_CreaComunitatLayout);
        A_CreaComunitatLayout.setHorizontalGroup(
            A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10))
                                .addGap(28, 28, 28)
                                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Crelacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Csembla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel14))
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(Cbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, A_CreaComunitatLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)))
                                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(Cafegeix1))
                                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(EliminaCsub)))
                                        .addGap(155, 155, 155)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                        .addComponent(CbuscaCat)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 366, Short.MAX_VALUE)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(113, 113, 113))
                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cpc)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, A_CreaComunitatLayout.createSequentialGroup()
                                .addComponent(CpcImp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(62, 62, 62)))
                        .addGap(169, 169, 169))))
        );
        A_CreaComunitatLayout.setVerticalGroup(
            A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Crelacio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                .addComponent(Csembla, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))
                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(CpcImp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Cbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CbuscaCat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jLabel18))
                                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(Cafegeix1)
                                                .addGap(18, 18, 18)
                                                .addComponent(EliminaCsub)))))
                                .addContainerGap())
                            .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGroup(A_CreaComunitatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel16)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, A_CreaComunitatLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47))))))
                    .addGroup(A_CreaComunitatLayout.createSequentialGroup()
                        .addComponent(Cpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(A_PantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(A_OpcionsClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_OpcionsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_BuscaCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(307, 307, 307)
                    .addComponent(A_BuscaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(307, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(341, 341, 341)
                    .addComponent(A_BuscaCatPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(341, 341, 341)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(650, 650, 650)
                    .addComponent(A_CreaComunitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(650, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(650, 650, 650)
                    .addComponent(A_CreaUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(650, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(A_PantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(A_OpcionsClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_OpcionsAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(A_BuscaCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(A_BuscaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(A_BuscaCatPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(279, 279, 279)
                    .addComponent(A_CreaComunitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(397, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(279, 279, 279)
                    .addComponent(A_CreaUsuari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(280, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleDescription("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        String user, pass;
        user= Username.getText();
        pass= Password.getText();
        if(!macro.getContUser().existsUser(user)) {
            Error aux = new Error(this,true);
            aux.ompletext("L'username no existeix, torna'l a introduir o crea una nova conta.");
            aux.setVisible(true);
        }
        else if(macro.getContUser().login(user, pass)){
            A_PantallaPrincipal.setVisible(false);
            if(macro.getContUser().isAdmin(user)) A_OpcionsAdmin.setVisible(true);
            else A_OpcionsClient.setVisible(true);
        }
        else {
            Error aux = new Error(this,true);
            aux.ompletext("Password incorrecte, si us plau, torna a introduir les dades.");
            aux.setVisible(true);
        }
         
       // }
       
// TODO add your handling code here:
    }//GEN-LAST:event_LoginActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        A_PantallaPrincipal.setVisible(false);
        A_CreaUsuari.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void EnrereCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrereCActionPerformed
        A_PantallaPrincipal.setVisible(true);
        A_OpcionsClient.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_EnrereCActionPerformed

    private void BuscaCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCategoriesActionPerformed
        A_OpcionsClient.setVisible(false);
        A_BuscaCat.setVisible(true);
        Collection<Categoria> auxc = macro.getGraf().getCategories();
        Object[] aux2 = new Object[auxc.size()];
        int cont = 0;
        Iterator<Categoria> it = auxc.iterator();
        while(it.hasNext()) {
            aux2[cont] = it.next().getNom();
            ++cont;
        }
        LlistaCateg.setListData(aux2);
    }//GEN-LAST:event_BuscaCategoriesActionPerformed

    private void BuscaCatPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaCatPagActionPerformed
        A_OpcionsClient.setVisible(false);
        A_BuscaCatPag.setVisible(true);
        Collection<Pagina> auxc = macro.getGraf().getPagines();
        Object[] aux2 = new Object[auxc.size()];
        int cont = 0;
        Iterator<Pagina> it = auxc.iterator();
        while(it.hasNext()) {
            aux2[cont] = it.next().getNom();
            ++cont;
        }
        LlistaPag1.setListData(aux2);
        Collection<Categoria> auxc1 = macro.getGraf().getCategories();
        Object[] aux3 = new Object[auxc1.size()];
        cont = 0;
        Iterator<Categoria> it2 = auxc1.iterator();
        while(it2.hasNext()) {
            aux3[cont] = it2.next().getNom();
            ++cont;
        }
        LlistaCateg1.setListData(aux3);
    }//GEN-LAST:event_BuscaCatPagActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    private void BOpCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOpCActionPerformed
        A_OpcionsClient.setVisible(true);// TODO add your handling code here:
        A_BuscaCat.setVisible(false);
    }//GEN-LAST:event_BOpCActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void BVisCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVisCatActionPerformed
        if(LlistaCateg.getSelectedIndices().length>0) {
            String hy = LlistaCateg.getSelectedValue().toString();
            VCategoria aux = new VCategoria(this,true);
            Categoria auxi = macro.getGraf().getCategoria(hy);
            aux.NomCat(auxi);
        }
        else {
            Error despistat = new Error(this,true);
            despistat.ompletext("Has de seleccionar algun element de la llista!");
            despistat.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_BVisCatActionPerformed

    private void BuscaPaginesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaPaginesActionPerformed
       A_OpcionsClient.setVisible(false);
       A_BuscaPag.setVisible(true);
        Collection<Pagina> auxc = macro.getGraf().getPagines();
        Object[] aux2 = new Object[auxc.size()];
        int cont = 0;
        Iterator<Pagina> it = auxc.iterator();
        while(it.hasNext()) {
            aux2[cont] = it.next().getNom();
            ++cont;
        }
        LlistaPag.setListData(aux2);
    }//GEN-LAST:event_BuscaPaginesActionPerformed

    private void BOpC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOpC1ActionPerformed
       A_OpcionsClient.setVisible(true);// TODO add your handling code here:
       A_BuscaPag.setVisible(false);
    }//GEN-LAST:event_BOpC1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void BVisPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVisPagActionPerformed
        if(LlistaPag.getSelectedIndices().length>0) {
            String hy = LlistaPag.getSelectedValue().toString();
            VPagina aux = new VPagina(this,true);
            Pagina auxi = macro.getGraf().getPagina(hy);
            aux.NomPag(auxi);
        }
        else {
            Error despistat = new Error(this,true);
            despistat.ompletext("Has de seleccionar algun element de la llista!");
            despistat.setVisible(true);
        }
    }//GEN-LAST:event_BVisPagActionPerformed

    private void BVisPag1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVisPag1ActionPerformed
       if(LlistaPag1.getSelectedIndices().length>0) {
            String hy = LlistaPag1.getSelectedValue().toString();
            VPagina aux = new VPagina(this,true);
            Pagina auxi = macro.getGraf().getPagina(hy);
            aux.NomPag(auxi);
        }
        else {
            Error despistat = new Error(this,true);
            despistat.ompletext("Has de seleccionar algun element de la llista!");
            despistat.setVisible(true);
        }
    }//GEN-LAST:event_BVisPag1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void BVisCat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVisCat1ActionPerformed
        if(LlistaCateg1.getSelectedIndices().length>0) {
            String hy = LlistaCateg1.getSelectedValue().toString();
            VCategoria aux = new VCategoria(this,true);
            Categoria auxi = macro.getGraf().getCategoria(hy);
            aux.NomCat(auxi);
        }
        else {
            Error despistat = new Error(this,true);
            despistat.ompletext("Has de seleccionar algun element de la llista!");
            despistat.setVisible(true);
        }
    }//GEN-LAST:event_BVisCat1ActionPerformed

    private void BOpC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOpC2ActionPerformed
        A_BuscaCatPag.setVisible(false);
        A_OpcionsClient.setVisible(true);
    }//GEN-LAST:event_BOpC2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void NouUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NouUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NouUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Error aux = new Error(this, true);
        String resultat;
        if(macro.getConjUsers().exists(NouUsername.getText())) resultat = "Aquest nom d'usuari ja existeix, si us plau, tria'n un altre";
        else  resultat = "Aquest nom d'usuari està lliure, endavant";
        aux.ompletext(resultat);
        aux.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NovaPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NovaPasswordActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        A_CreaUsuari.setVisible(false);
        A_PantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(macro.getConjUsers().exists(NouUsername.getText())) {
          Error aux = new Error(this, true);
          aux.ompletext("Aquest nom d'usuari ja existeix, si us plau, tria'n un altre");
          aux.setVisible(true);
        }
        else if(NovaPassword.getText().length()==0) {
          Error aux = new Error(this, true);
          aux.ompletext("Escriu una contrassenya siusplau");
          aux.setVisible(true);
        }
        else {
            macro.getContUser().addUser(NouUsername.getText(), NovaPassword.getText());
            Error aux = new Error(this, true);
          aux.ompletext("Felicitats, conta cread!");
          aux.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private Boolean buida;
    private void CreaCercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreaCercaActionPerformed
        A_OpcionsClient.setVisible(false);
        buida=true;
        Collection<Categoria> aux = macro.getGraf().getCategories();
        Iterator<Categoria> it = aux.iterator();
        Object[] csub= new Object[aux.size()];
        int cont = 0;
        while(it.hasNext()){
            csub[cont] = it.next().getNom();
            ++cont;
        }
        LCTotes.setListData(csub);
        A_CreaComunitat.setVisible(true);
    }//GEN-LAST:event_CreaCercaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CbuscaCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbuscaCatActionPerformed
        String busca = Cbusca.getText();
        Collection<Categoria> aux = macro.getGraf().getCategories();
        Iterator<Categoria> it = aux.iterator();
        Object[] csub= new Object[aux.size()];
        int cont = 0;
        while(it.hasNext()){
            String nom =it.next().getNom();
            if(nom.contains(busca)) {
                csub[cont] = nom;
                ++cont;
            }
        }
        LCTotes.setListData(csub);
    }//GEN-LAST:event_CbuscaCatActionPerformed
        
    private void Cafegeix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cafegeix1ActionPerformed
       // Component quina = LTotes.getComponent(LTotes.getSelectedIndex());
       //DefaultListModel listModel = new DefaultListModel();
    	modelo.addElement(LCTotes.getSelectedValue());
           //Lsub.setListData(modelo);
        /*Object aux = LTotes.getSelectedValue();
        
        //LTotes.remove(LTotes.getSelectedIndex());
        Object[] nou;
        if(buida) {
            System.out.println("afegeixo x primer: "+aux);
            //System.out.println("mida sub:"+Lsub.get+ ", mida totes: "+ LTotes.getSize());
            System.out.println("comp sub:"+Lsub.getComponents().length + ", mida totes: "+ LTotes.getComponents().length);
            nou = new Object[1];
            nou[0] = aux;
            buida=false;
        }
        else {
            System.out.println("afegeixo x altres: "+aux);
            Object[] csub = Lsub.getComponents();
            int mida = Lsub.getComponentCount();
            System.out.println("mida abans: "+mida);
            nou = new Object[mida+1];
            int cont = 0;
            while(cont <= mida) {
                System.out.println("Entro al while amb cont:"+cont+" i "+ csub[cont]);
                nou[cont] =csub[cont];
                ++cont;
            }
            nou[cont] = aux;
        }
        Lsub.setListData(nou);*/
        /*lm2 = (DefaultListModel)LTotes.getModel();
        lm1  =  (DefaultListModel)Lsub.getModel();
        if(lm2 == null) {
        	lm2 = new DefaultListModel();
        	LTotes.setModel(lm2);
        }
        lm2.addElement(LTotes.getSelectedValue());
        lm1.removeElement(LTotes.getSelectedValue());  */ 
        /*  ListModel listModel = Lsub.getModel();
       // listModel.addElement(LTotes.getSelectedValue());
       if(listModel ==null) {
           Lsub.setModel(LTotes.getModel());
       }
       LTotes.remove(LTotes.getSelectedIndex());
       Lsub.add(LTotes.getComponent(LTotes.getSelectedIndex()));
       Component[] aux = LTotes.getComponents();
       int cont = aux.length;
       Vector auxi = new Vector();
       while(cont >=0) {
           auxi.add(aux[cont]);
       }
       Lsub.setVisible(true);
       LTotes.setVisible(true);
       //Lsub.add7
       // Lsub.clearSelection();*/
    }//GEN-LAST:event_Cafegeix1ActionPerformed

    private void EliminaCsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminaCsubActionPerformed
          if(modelo.getSize()>0){
              int n = Lsub.getSelectedIndex();
              modelo.removeElementAt(n);
          }
    }//GEN-LAST:event_EliminaCsubActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AfegirFitxer aux = new AfegirFitxer(this,true);
        aux.passarmacro(macro);
        aux.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterficiaProva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterficiaProva().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A_BuscaCat;
    private javax.swing.JPanel A_BuscaCatPag;
    private javax.swing.JPanel A_BuscaPag;
    private javax.swing.JPanel A_CreaComunitat;
    private javax.swing.JPanel A_CreaUsuari;
    private javax.swing.JPanel A_OpcionsAdmin;
    private javax.swing.JPanel A_OpcionsClient;
    private javax.swing.JPanel A_PantallaPrincipal;
    private javax.swing.JButton BOpC;
    private javax.swing.JButton BOpC1;
    private javax.swing.JButton BOpC2;
    private javax.swing.JButton BVisCat;
    private javax.swing.JButton BVisCat1;
    private javax.swing.JButton BVisPag;
    private javax.swing.JButton BVisPag1;
    private javax.swing.JButton BuscaCatPag;
    private javax.swing.JButton BuscaCategories;
    private javax.swing.JButton BuscaCerques;
    private javax.swing.JButton BuscaPagines;
    private javax.swing.JButton Cafegeix1;
    private javax.swing.JTextField Cbusca;
    private javax.swing.JButton CbuscaCat;
    private javax.swing.JTextField Cpc;
    private javax.swing.JSlider CpcImp;
    private javax.swing.JButton CreaCerca;
    private javax.swing.JSlider Crelacio;
    private javax.swing.JSlider Csembla;
    private javax.swing.JButton EliminaCsub;
    private javax.swing.JButton EnrereC;
    private javax.swing.JButton Exit;
    private javax.swing.JList LCTotes;
    private javax.swing.JList LPTotes;
    private javax.swing.JList LlistaCateg;
    private javax.swing.JList LlistaCateg1;
    private javax.swing.JList LlistaPag;
    private javax.swing.JList LlistaPag1;
    private javax.swing.JButton Login;
    private javax.swing.JList Lsub;
    private DefaultListModel modelo;
    private javax.swing.JTextField NouUsername;
    private javax.swing.JTextField NovaPassword;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
